# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: robertbindar/mariadb_jupyter_kernel:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt install -y libxml2-dev libxslt1-dev zlib1g-dev pkg-config
          conda activate py38
          conda env list
          python -m pip install -r dev-requirements.txt
          python setup.py develop

      - name: Test with pytest
        run: |
          pytest -v --maxfail=2 --color=yes mariadb_kernel/tests/
